framework:
    messenger:
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                    jitter: 0.3
            failed: "doctrine://default?queue_name=failed&auto_setup=0"

        routing:
            App\Worker\Message\ProcessWebhookEvent: async
